### ISSUE TITLE
New Challenge - Create string that requires an escape character and/or literal string

### ISSUE THREAD

**Issue by kevmoens** [kevmoens/Ellabit#14]
Create a challenge that has the user create a string that would require using an escape character and/or literal string

Notes from [Microsoft Learn](https://learn.microsoft.com/en-us/training/modules/csharp-basic-formatting/2-exercise-character-escape-sequences)
- Use character escape sequences when you need to insert a special character into a literal string, like a tab \t, new line \n, or a double quotation mark \".
- Use an escape character for the backslash \\ when you need to use a backslash in all other scenarios.
- Use the @ directive to create a verbatim string literal that keeps all whitespace formatting and backslash characters in a string.

Example
Console.WriteLine("Hello "World"!"); --fail
Console.WriteLine("Hello \"World\"!");

Console.WriteLine("c:\source\repos"); --fail
Console.WriteLine(@"c:\source\repos");
Console.WriteLine("c:\\source\\repos");

Console.WriteLine("Test\nNew Line");

**Comment by wolf-361** [comment]
I would be interested on working on this, just don't have much experience

**Comment by kevmoens** [comment]
Try it out and submit a pull request.
Let me know if you need any information.

**Comment by wolf-361** [comment]
Great thx ! I'll look into it tomorrow

Just to make sure  I make a new challenge #191 named something like escape string ?
