### ISSUE TITLE
New Challenge - Use string.Empty for validation

### ISSUE THREAD

**Issue by kevmoens** [kevmoens/Ellabit#15]
String.Empty when compared will return true if it is null or an empty string ("")
Make a challenge returning a boolean value if the string passed in is equal to string.Empty

**Comment by wolf-361** [comment]
How is this different from challenge #045 Is the string empty?

**Comment by kevmoens** [comment]
Good point that #45 checks for "".  Yet while working this past week checking if a string is equal to string.Empty we found it handles null.  So we just need a new test on challenge #45

**Comment by wolf-361** [comment]
ok !!

**Comment by wolf-361** [comment]
there is also the IsNullOrEmpty(str) method

**Comment by kevmoens** [comment]
I think if they use either that would be sufficient.  

On a side note for a new challenge, one could be made for checking string.IsNullOrWhitespace

**Comment by wolf-361** [comment]
Do you want me to open an issue for it then ?

**Comment by kevmoens** [comment]
Sure
