### ISSUE TITLE
Problem with .tt files

### ISSUE THREAD

**Issue by paulvanbladel** [kevmoens/Ellabit#45]
Very nice project. Well done !
I'm getting a problem when I run ad hoc the tt files by right clicking "run custom tool". The generated code gets completely messed up.
Take care

**Comment by kevmoens** [comment]
Can you give me more detail and I'll see if I can answer.

**Comment by paulvanbladel** [comment]
Thanks Kevin.
https://github.com/kevmoens/Ellabit/blob/master/Ellabit/OmniSharp/OmniSharpCompletionService.tt 
is a .tt file, so code generation takes place based on the tt template.
In visual studio you can right click on the file and select "run custom tool".
![image](https://user-images.githubusercontent.com/4886272/218248490-dea94d66-dca6-4ff1-8798-c07e2310e1ef.png)
Well, try that and, at least on my side, the code is updated and will no longer build correctly.

**Comment by kevmoens** [comment]
While implementing OmniSharp to work with BlazorMonaco these files are referenced and required.  You do not need to run anything against these files before working with the project.
An example project I might have referenced is: https://github.com/Apollo3zehn/MonacoBlazorSample
They also have these files in their project.

**Comment by paulvanbladel** [comment]
Ok Thanks a lot Kevin for trying to clarify.
